name = "MajoranaReps"
uuid = "4d2ab388-4915-11ec-2296-b707a6cee44b"
authors = ["Mikael Fremling <micke.fremling@gmail.com>"]
version = "0.1.0"

[deps]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"


[compat]
julia = "1"
